# Generated by Django 5.0.7 on 2024-08-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutTheTicketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_1", models.TextField()),
                ("description_2", models.TextField()),
            ],
            options={
                "verbose_name": "About the Ticket Data",
                "verbose_name_plural": "About the Ticket Data",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.CreateModel(
            name="HeroData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Hero Data",
                "verbose_name_plural": "Hero Data",
            },
        ),
        migrations.CreateModel(
            name="OnBoardingToTheWalletData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Onboarding to the Wallet Data",
                "verbose_name_plural": "Onboarding to the Wallet Data",
            },
        ),
        migrations.CreateModel(
            name="TicketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Ticket Data",
                "verbose_name_plural": "Ticket Data",
            },
        ),
        migrations.CreateModel(
            name="VideoSectionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="video_thumbnails/"
                    ),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name": "Video Section Data",
                "verbose_name_plural": "Video Section Data",
            },
        ),
        migrations.CreateModel(
            name="ImageOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images_onboarding/")),
                (
                    "onboarding_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="data.onboardingtothewalletdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Onboarding",
                "verbose_name_plural": "Image Onboardings",
            },
        ),
    ]
