# Generated by Django 5.0.7 on 2024-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginPageData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Hero Data",
                "verbose_name_plural": "Hero Data",
            },
        ),
    ]
